wandb_version: 1

model_config:
  desc: null
  value:
    model_name: VGG_16
    n_class: 10
trainer_config:
  desc: null
  value:
    epochs: 10
    batch_size: 64
    learning_rate: 0.5
    device: mps
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691597917.37413
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 4
      - 5
