name: frft-demo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.7
  - wandb=0.15.7
  - ipykernel=6.25.0
  - matplotlib=3.7.2
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - tqdm=4.65.0
  - python-dotenv=1.0.0
  - pip
  - pip:
      - torch-frft
