wandb_version: 1

batch_size:
  value: 40
classes:
  value: 10
dataset:
  value: CIFAR-10
device:
  value: cpu
epochs:
  value: 5
learning_rate:
  value: 0.32785219165071117
model_name:
  value: VGG_11_DFRFT
momentum:
  value: 0.9
weight_decay:
  value: 0.0005
