method: grid
project: frft-demo
metric:
  name: test/test_accuracy
  goal: maximize
parameters:
  patience:
    value: 10
  max_epochs:
    value: 50
  gpu_id:
    value: 2
  model_name:
    value: "ResNet50_DFRFT"
  n_class:
    value: 200
  dataset_name:
    value: "CUB2011"
  # Data Handler CONFIG
  batch_size:
    values: [64,32]
 
  multi_gpu:
    value: False
  # Optimizer CONFIG
  lr:
    values: [0.001,0.005]
   
  wd:
    values: [0.0001] #, 0.05]
  momentum:
    value: 0.9
  early_stop_verbose:
    value: True
  train_slice:
    value: 1
  test_slice: 
     value: 1
  n_runs:
    value: 30
  

# TODO: You can also use hyperband early stopping, check the details from wandb documentation
  
