method: grid
project: frft-demo
metric:
  name: test/test_accuracy
  goal: maximize
parameters:
  patience:
    value: 20
  max_epochs:
    values: [50]
  gpu_id:
    value: 3
  model_name:
    value: "ResNet34_FFT"   # "ResNet152_DFRFT" , "ResNet152_FRFT"  ,"ResNet152"    
  n_class:
    value: 10
  dataset_name:
    value: "CIFAR-10"   
  # Data Handler CONFIG
  batch_size:
    values: [64]
  multi_gpu:
    value: False
  # Optimizer CONFIG
  lr:
    values: [0.001]
  wd:
    values: [0.0001] #, 0.05]
  momentum:
    value: 0.9
  early_stop_verbose:
    value: True
  train_slice:
    value: 1
  test_slice: 
     value: 1
  n_runs:
    value: 30

  

# TODO: You can also use hyperband early stopping, check the details from wandb documentation
  


#Use this setting for base models:
#Same scheduler and optimizer for all

# It is more fair to compare FFT/FRFT based method and Time domain method using pretrained models with a slight difference in epoch size
#TIME DOMAIN: BS=64,EPOCH:30-35, LR:0.001
#FFT/FRFT DOMAIN: BS=64, EPOCH:50, LR:0.001



