wandb_version: 1

batch_size:
  value: 96
classes:
  value: 10
dataset:
  value: CIFAR-10
device:
  value: cpu
epochs:
  value: 5
learning_rate:
  value: 0.1866400014341585
model_name:
  value: VGG_11_FRFT
