wandb_version: 1

batch_size:
  value: 208
classes:
  value: 10
dataset:
  value: CIFAR-10
device:
  value: cpu
epochs:
  value: 5
learning_rate:
  value: 0.3110685092490861
model_name:
  value: VGG_11_FFT
