wandb_version: 1

batch_size:
  desc: null
  value: 104
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: CIFAR-10
device:
  desc: null
  value: cpu
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.4690389856968899
model_name:
  desc: null
  value: VGG_11_FRFT
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692004179.205954
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.11.4
      5: 0.15.8
      8:
      - 5
