wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.5
weight_decay:
  desc: null
  value: 0.0005
momentum:
  desc: null
  value: 0.9
device:
  desc: null
  value: cpu
model_name:
  desc: null
  value: VGG_11_FRFT
n_class:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692011157.593584
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 4
      - 5
