wandb_version: 1

batch_size:
  value: 160
classes:
  value: 10
dataset:
  value: CIFAR-10
device:
  value: cpu
epochs:
  value: 5
learning_rate:
  value: 0.31646932393597677
model_name:
  value: VGG_11_FRFT
